name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://npm.pkg.github.com/'

    - name: Publish to GitHub Packages
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}

    - name: Setup Node.js for npm
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'

    - name: Prepare for npm publish
      run: |
        sed -i 's/"name": "@willdgit\/webs.js"/"name": "webs.js"/' package.json

    - name: Publish to npm
      run: npm publish --registry https://registry.npmjs.org/
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM }}
